# Generated by Django 4.0.6 on 2024-02-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='medical',
            field=models.CharField(choices=[('primera', 'PRIMERA CLASE'), ('segunda', 'SEGUNDA CLASE')], default='1', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='medical_date',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
