# Generated by Django 4.0.6 on 2024-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoth', '0002_user_medical_user_medical_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oaci_id', models.CharField(max_length=4)),
                ('iata_id', models.CharField(max_length=3)),
                ('airport_name', models.CharField(max_length=80)),
                ('display_name', models.CharField(max_length=80)),
            ],
        ),
    ]
