# Generated by Django 4.0.6 on 2024-05-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoth', '0003_airports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logbook',
            name='destination',
            field=models.CharField(blank=True, default=0, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='logbook',
            name='origin',
            field=models.CharField(blank=True, default=0, max_length=80, null=True),
        ),
    ]
